const walletTypes = {
    SAVE_WALLET_HISTORY_START: 'SAVE_WALLET_HISTORY_START',
    GET_WALLET_HISTORY_START: 'GET_WALLLET_HISTORY_START',
    UPDATE_WALLET_HISTORY_START: 'UPDATE_WALLET_HISTORY_START',
    SET_WALLET_HISTORY_START: 'SET_WALLET_HISTORY_START',
  };
  
  export default walletTypes;